name: build-deploy.yml
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Rename env file
        run: |
          mv .env.example .env
          cat .env

      - name: Export .env to Github Environment
        run: |
          grep -v '^#' .env | grep -v '^$' >> $GITHUB_ENV
      - name: Confirm .env loaded
        run: |
          echo "User = POSTGRES_USER"
         
      - name: Run unit tests
        run: ./mvnw test

      - name: Run integration tests
        run: ./mvnw verify -DskipUnitTests


